### 📖1. Import NumPy as np

In [ ]:
import numpy as np

### 📖2. Create an array from this list

In [ ]:
mylist = [9, 8, 7, 6, 5, 4, 3, 2, 1]
myarray = np.array(mylist)
myarray

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

### 📖3. Reshape the array you just created to the shape 3x3

In [ ]:
reshaped = myarray.reshape(3,3)
reshaped

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### 📖4. Print the shape of the array you just  reshaped

In [ ]:
reshaped.shape

(3, 3)

### 📖5. Create an array of 25 fives and reshape them to a shape of 5x5

In [ ]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 📖6. Create an array of 10 random numbers between 0 and 1

In [ ]:
arr = np.random.rand(10)
arr

array([0.90680511, 0.99742819, 0.77200172, 0.24154789, 0.45313473,
       0.21942111, 0.70674746, 0.05677302, 0.18332823, 0.69515142])

### 📖7. Create a 10x10 matrix of random integers between 0 and 255 (both inclusive)

In [ ]:
arr = np.random.randint(0, 256, (10, 10))
arr

array([[150, 241, 125, 241, 111, 145, 153, 116, 189,  12],
       [128, 100,  98,  34, 201, 101, 255, 230, 221, 145],
       [ 53, 146, 213, 130,  18,  81, 119,  41, 208, 238],
       [ 28, 201, 230, 157, 138, 122, 153, 188, 215, 234],
       [ 69, 182, 208,  33, 253,  14, 232, 166, 148, 197],
       [217,  97,  17, 202,  45, 218, 194, 245, 148,   4],
       [227,  83, 175,  15, 101, 192, 182, 185, 103,  58],
       [116, 235, 206,  63, 152, 181, 234, 252, 129, 197],
       [144, 197, 190, 231,   7,  30, 193, 237, 224,  46],
       [135,  59, 187,  26,  43, 176, 180,  41,   0, 241]])

### 📖8. based on your previous matrix, get the item which is in row 6 and column 4

In [ ]:
arr[5, 3]

202

### 📖9. Based on your previous matrix, select the last value from every row

In [ ]:
arr[:, -1]

array([ 12, 145, 238, 234, 197,   4,  58, 197,  46, 241])