### 📖Numpy
"NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays." [Wikipedia](https://en.wikipedia.org/wiki/NumPy)

Numpy can efficiently handle arrays (a n-dimensional dataseries of values) and do calculations with them.

In [ ]:
#Before we can use numpy, we have to import numpy
import numpy as np

***
### 📖List to array

In [ ]:
#A simple Numpy arrray is similar to a Python List. It is a sequence of Data.
#Therefore we can create an array from a list
mylist = [1,2,3]
type(mylist) #Check the type

list

In [ ]:
#Turn list to an arrray
np.array(mylist)

array([1, 2, 3])

In [ ]:
#However, if we want to change the list to an arrray permanently, we have to assign it to a new variable
myarr = np.array(mylist)
type(myarr)

numpy.ndarray


### 📖Transform a nested list into a two-dimensional numpy array

In [ ]:
mylist = [[1,2,3], [4,5,6], [7,8,9]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
mymatrix = np.array(mylist)
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

This is called a 2D array, as it has a X and a Y  axis. They are also refered to as rows and columns

In [ ]:
mymatrix.shape

(3, 3)

The shape shows that it is a 3x3 matrix

***
### 📖Numpy buit in methods

### 📖np.arange
Creates an array of numberst between a start- (inclusive) and a stop value (exclusive) using a defined step (default is 1)

In [ ]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### 📖np.ones
creates an array of ones (type: float) with a user-defined length

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

you can specify the shape of the array by providing a tuple with the desired shape

In [ ]:
np.ones((3, 5)) #This one will have 3 rows and 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 📖np.zeros
creates an array of zeros (type: float) with a user-defined length

In [ ]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

you can specify the shape of the array by providing a tuple with the desired shape

In [ ]:
np.zeros((8, 10)) #This one will have 8 rows and 10 columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 📖Broadcasting operations to every value in matrices
In numpy you can do all kinds of operations with arrays. For example, you can simply add a value to each element. This is not possible within normal Python lists

In [ ]:
np.ones((4, 6)) + 6 #A 6 will be added to every element

array([[7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7.]])

In [ ]:
np.ones(10) * 100

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

### 📖np.linspace
Creates an array with linearly spaced numbers. Needs a startvalue, stopvalue and the number of values that should be linearly spaced between start- and stop value.
Different to np.arrange it can also generate float values and its start and stop values are both inclusive

In [ ]:
np.linspace(0 , 10, 3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0 , 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### 📖np.random.rand
Creates random samples of a uniform distribution between 0 and 1 (every value between 0 and 1 has the same probability of getting chosen)

In [ ]:
np.random.rand(3)

array([0.3632668 , 0.13023271, 0.52157785])

In [ ]:
np.random.rand(5, 5)

array([[0.36612915, 0.87792682, 0.05203252, 0.02764891, 0.31170575],
       [0.68932229, 0.79134956, 0.01812732, 0.58447655, 0.95384179],
       [0.79142992, 0.28532116, 0.03583618, 0.05431546, 0.3663545 ],
       [0.39108946, 0.52651586, 0.84537835, 0.12563322, 0.26668021],
       [0.56569679, 0.52006251, 0.26980199, 0.80459768, 0.15316512]])

### 📖np.random.randn
Creates samples from the standard normal distribution (mean = 0, stdv =1)

In [ ]:
np.random.randn(10)
#if you want to create your own standard distribution with a mean and a stdv, use np.random.normal

array([-0.2197954 ,  0.59107236,  0.17937833,  1.87462908, -0.12288244,
        0.93291376,  0.06278072, -1.60037817,  0.86758024, -0.64914352])

### 📖np.random.randint
Creates random integers between a low (inclusive) and a high value (exclusive) and a specific size

In [ ]:
np.random.randint(1, 100)

17

In [ ]:
#You can additionally specify the size/shape
np.random.randint(1, 100, 10)

array([52,  4, 32, 98, 89, 47, 26, 49, 26, 39])

### 📖np.reshape
Changes the dimensions/shape of an array to the desired format. Keep in mind that the provided dimensions have to be compatiple with the amount of values stored in the array.

In [ ]:
#create an array
arr = np.arange(25)
arr.shape

(25,)

In [ ]:
reshaped = arr.reshape(5, 5)
reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
reshaped.shape

(5, 5)

We can not set the provided array with its 25 elements to a shape of 3x5, has such a shape would only be capable to hold 15 values, however, 25 are provided!

### 📖np.min(),  np.max()
Returns the min or max value of an array

In [ ]:
arr = np.random.randint(0, 50, 20)
print(np.min(arr))
print(np.max(arr))

2
47


### 📖np.argmin(), np.argmax()
Returns the index location of the min or max value

In [ ]:
print(np.argmin(arr))
print(np.argmax(arr))

11
9


### 📖np.dtype
Returns the datatype of an arrray

In [ ]:
arr.dtype

dtype('int32')

### 📖Selections and indexing
Selecting elements from an arrray is very similar to selecting elements in Python lists

### 📖Indexing 1D arrays

In [ ]:
#Create an arrray that we can use
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#pass the index of an element to select it
arr[4]

4

### 📖Slicing 1D arrays

In [ ]:
#selecting values between two indices [start(included) : end(excluded)]
arr[2:6]

array([2, 3, 4, 5])

In [ ]:
#selecting up to an index [: end(excluded)]
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
#selecting from an index onward [start(including):]
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### 📖Indexing 2D arrays

In [ ]:
#Create a 2d array
arr_2D = np.array([[15,35,60], [25, 55, 45], [10, 20, 30]])
print(arr_2D.shape)
arr_2D

array([[15, 35, 60],
       [25, 55, 45],
       [10, 20, 30]])

In [ ]:
#Select a row from the array
arr_2D[1]

array([25, 55, 45])

In [ ]:
#Select a single item by also providing the column
arr_2D[1][1]

55

In [ ]:
#To make it shorter, we can also put the index of the item in a single []
arr_2D[1, 1]

55

### 📖Slicing 2D arrays

In [ ]:
#Lets try to select the two last columns from the first two rows

#Select the first two rows:
arr_2D[:2]

array([[15, 35, 60],
       [25, 55, 45]])

In [ ]:
#Select the last two items from those two rows
arr_2D[:2, 1:]

array([[35, 60],
       [55, 45]])

In [ ]:
#Lets try to select the first value of every row
#To select all elements of a dimension, we can use ':'

arr_2D[:, 0] #This means: From all rows ':', select the first item/ the item in column 0

array([15, 25, 10])

### 📖Conditional selection
Only keeps items that fullfill the condition

In [ ]:
arr = np.arange(0, 11)
print(arr)

arr[arr > 6]

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 7,  8,  9, 10])

### 📖Array copies
It is important to know, that a selection of an array still points to its original array, even though it has been assigned to a new variable

In [ ]:
#Example:
arr = np.arange(0, 11)
print(arr)

#Do a selection and store the selection in a new variable
new_arr = arr[:5]
new_arr

array([0, 1, 2, 3, 4])

In [ ]:
#Set all values in the selection to -999 (we need '[:]' to select all values from our selection)
new_arr[:] = -999
new_arr

array([-999, -999, -999, -999, -999])

In [ ]:
#it first seems like we have just changed the values from our selection to a new value, but let us look at the original array
arr

array([-999, -999, -999, -999, -999,    5,    6,    7,    8,    9,   10])

To prevent the original array to be changed, we can create copies of it

In [ ]:
arr = np.arange(0, 11)
new_arr = arr.copy()[:5]
new_arr

array([0, 1, 2, 3, 4])

### 📖Operations across axis
With np.max() and np.min() we already got in contact with numpy operations. Besides those two operations there are many others, such as np.mean(), np.sum(), np.log(my_array), np.sin(my_array) etc. [More information about operations](https://www.pluralsight.com/guides/overview-basic-numpy-operations)

In a multidimensional array we can specify through which axis we want to do our calculations
![grafik.png](attachment:grafik.png)
[Source](https://www.statology.org/numpy-axis/)

In [ ]:
arr = np.arange(0,20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#calculate the sum of all items
np.sum(arr)

190

In [ ]:
#calculate the sum across the rows/along the columns/along the vertical axis (y)
np.sum(arr, axis=0)

array([30, 34, 38, 42, 46])

In [ ]:
#calculate the sum across the coolumns/along the rows/along the horizontal axis (x)
np.sum(arr, axis=1)

array([10, 35, 60, 85])